### ISSUE TITLE
Argument isn't numeric

### ISSUE THREAD

**Issue by mahemoff** [linode/linode-cli#162] opened 2019-12-04 17:55 UTC
```Default datacenter when deploying a new Linode. (Optional)                                           
Valid options are:                                                                                    
  1 - atlanta                                                                                         
  2 - dallas                                                                                          
  3 - frankfurt                                                                                       
  4 - fremont                                                                                        
  5 - london                                                                                         
  6 - mum1                                                                                            
  7 - newark                                                                                          
  8 - shinagawa1                                                                                      
  9 - singapore                                                                                       
 10 - syd1                                                                                            
 11 - tor1                                                                                            
Choose[ 1-11 ] or Enter to skip>> 7                                                                   
                                                                                                      
Default plan when deploying a new Linode. (Optional)                                                  
Valid options are:                                                                                    
Argument "192GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521.
Argument "90GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521.
Argument "24GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521. 
Argument "300GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521.
Argument "128GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521.
Argument "8GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521.  
Argument "48GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521.
Argument "96GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521.
Argument "2GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521. 
Argument "150GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521.
Argument "96GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521.
Argument "1GB" isn't numeric in numeric comparison (<=>) at /usr/share/perl5/Linode/CLI.pm line 521. 
```

**Comment by Dorthu** [comment] 2019-12-04 18:01
This looks like a duplicate of #163 - closing

**Closed by Dorthu** 2019-12-04 18:01 UTC
