### ISSUE TITLE
profile logins-list crashes

### ISSUE THREAD

**Issue by trainmeditations** [linode/linode-cli#215] opened 2020-12-07 03:51 UTC
I was just trying out this tool when I found one of the commands causes a crash to stack trace. I thought it might have been because I was using a read only token but switching to a read-write token for all scopes didn't fix it.

Redacted stack trace:

```
Traceback (most recent call last):
  File "[home]\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "[home]\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "[home]\AppData\Local\Programs\Python\Python39\Scripts\linode-cli.exe\__main__.py", line 7, in <module>
  File "[home]\appdata\local\programs\python\python39\lib\site-packages\linodecli\__init__.py", line 436, in main
    cli.handle_command(parsed.command, parsed.action, args)
  File "[home]\appdata\local\programs\python\python39\lib\site-packages\linodecli\cli.py", line 556, in handle_command
    operation.process_response_json(result.json(), self.output_handler)
  File "[home]\appdata\local\programs\python\python39\lib\site-packages\linodecli\operation.py", line 230, in process_response_json
    handler.print(self.response_model, json)
  File "[home]\appdata\local\programs\python\python39\lib\site-packages\linodecli\output.py", line 45, in print
    self._table_output(header, data, columns, title, to)
  File "[home]\appdata\local\programs\python\python39\lib\site-packages\linodecli\output.py", line 87, in _table_output
    content.append([attr.render_value(model) for attr in columns])
  File "[home]\appdata\local\programs\python\python39\lib\site-packages\linodecli\output.py", line 87, in <listcomp>
    content.append([attr.render_value(model) for attr in columns])
  File "[home]\appdata\local\programs\python\python39\lib\site-packages\linodecli\response.py", line 45, in render_value
    value = self._get_value(model)
  File "[home]\appdata\local\programs\python\python39\lib\site-packages\linodecli\response.py", line 30, in _get_value
    value = value[part]
KeyError: 'data'
```

**Comment by Dorthu** [comment] 2020-12-07 18:51
Thanks for the report.  I can reproduce this with a read/write token.  Lookin' into it now

**Comment by Dorthu** [comment] 2020-12-07 19:04
This behavior was caused by a spec error.  The API spec was updated here: https://github.com/linode/linode-api-docs/pull/370. Once that's merged, the new CLI release should correct this behavior.

**Comment by LBGarber** [comment] 2022-09-06 17:23
Hey @trainmeditations!
Just checking in to see if this issue has been resolved for you.

**Comment by trainmeditations** [comment] 2022-09-06 20:25
It's not a problem I've encountered recently and I'd completely forgotten about it. I've got no idea why I didn't seem to specify the command that caused it in my original report but it looks like it was understood at the time.

**Comment by LBGarber** [comment] 2022-09-06 20:43
Thanks for the info! I'll go ahead and close out this issue.

**Closed by LBGarber** 2022-09-06 20:43 UTC
